# Generated by Django 6.0.1 on 2026-08-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_transaction_profile_alter_transaction_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fetched_at', models.DateTimeField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_price', to='project.stock')),
            ],
        ),
    ]
